name:                spotifyctl
version:             0.1.0.0
github:              "delirehberi/spotifyctl"
license:             BSD3
author:              "Emre YILMAZ"
maintainer:          "z@emre.xyz"
copyright:           "2020 Emre YILMAZ"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/delirehberi/spotifyctl#readme>

dependencies:
- base >= 4.7 && < 5
- raw-strings-qq 
- http-types
- bytestring
- utf8-string
- wai
- warp 
- async 
- aeson
- base64-bytestring
- wreq
- lens
- lens-aeson
- http-client
- hspec
- QuickCheck 
- directory

library:
  source-dirs: src

executables:
  spotifyctl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spotifyctl

tests:
  spotifyctl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spotifyctl
    - hspec
